# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
#
# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from typing import Any


@dataclass
class DenseNetConf:
    _target_: str = "torchvision.models.densenet.DenseNet"
    growth_rate: Any = 32
    block_config: Any = (6, 12, 24, 16)
    num_init_features: Any = 64
    bn_size: Any = 4
    drop_rate: Any = 0
    num_classes: Any = 1000
    memory_efficient: Any = False
