# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
#
# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from typing import Any


@dataclass
class GoogLeNetConf:
    _target_: str = "torchvision.models.googlenet.GoogLeNet"
    num_classes: Any = 1000
    aux_logits: Any = True
    transform_input: Any = False
    init_weights: Any = None
    blocks: Any = None
