# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
#
# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from omegaconf import MISSING
from typing import Any


@dataclass
class MNASNetConf:
    _target_: str = "torchvision.models.mnasnet.MNASNet"
    alpha: Any = MISSING
    num_classes: Any = 1000
    dropout: Any = 0.2
