# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
#
# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from omegaconf import MISSING
from typing import Any


@dataclass
class ResNetConf:
    _target_: str = "torchvision.models.resnet.ResNet"
    block: Any = MISSING
    layers: Any = MISSING
    num_classes: Any = 1000
    zero_init_residual: Any = False
    groups: Any = 1
    width_per_group: Any = 64
    replace_stride_with_dilation: Any = None
    norm_layer: Any = None
