# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
#
# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from omegaconf import MISSING
from typing import Any


@dataclass
class BCELossConf:
    _target_: str = "torch.nn.modules.loss.BCELoss"
    weight: Any = MISSING  # Optional[Tensor]
    size_average: Any = None
    reduce: Any = None
    reduction: str = "mean"


@dataclass
class BCEWithLogitsLossConf:
    _target_: str = "torch.nn.modules.loss.BCEWithLogitsLoss"
    weight: Any = MISSING  # Optional[Tensor]
    size_average: Any = None
    reduce: Any = None
    reduction: str = "mean"
    pos_weight: Any = MISSING  # Optional[Tensor]


@dataclass
class CosineEmbeddingLossConf:
    _target_: str = "torch.nn.modules.loss.CosineEmbeddingLoss"
    margin: float = 0.0
    size_average: Any = None
    reduce: Any = None
    reduction: str = "mean"


@dataclass
class CTCLossConf:
    _target_: str = "torch.nn.modules.loss.CTCLoss"
    blank: int = 0
    reduction: str = "mean"
    zero_infinity: bool = False


@dataclass
class L1LossConf:
    _target_: str = "torch.nn.modules.loss.L1Loss"
    size_average: Any = None
    reduce: Any = None
    reduction: str = "mean"


@dataclass
class HingeEmbeddingLossConf:
    _target_: str = "torch.nn.modules.loss.HingeEmbeddingLoss"
    margin: float = 1.0
    size_average: Any = None
    reduce: Any = None
    reduction: str = "mean"


@dataclass
class KLDivLossConf:
    _target_: str = "torch.nn.modules.loss.KLDivLoss"
    size_average: Any = None
    reduce: Any = None
    reduction: str = "mean"
    log_target: bool = False


@dataclass
class MarginRankingLossConf:
    _target_: str = "torch.nn.modules.loss.MarginRankingLoss"
    margin: float = 0.0
    size_average: Any = None
    reduce: Any = None
    reduction: str = "mean"


@dataclass
class MSELossConf:
    _target_: str = "torch.nn.modules.loss.MSELoss"
    size_average: Any = None
    reduce: Any = None
    reduction: str = "mean"


@dataclass
class MultiLabelMarginLossConf:
    _target_: str = "torch.nn.modules.loss.MultiLabelMarginLoss"
    size_average: Any = None
    reduce: Any = None
    reduction: str = "mean"


@dataclass
class MultiLabelSoftMarginLossConf:
    _target_: str = "torch.nn.modules.loss.MultiLabelSoftMarginLoss"
    weight: Any = MISSING  # Optional[Tensor]
    size_average: Any = None
    reduce: Any = None
    reduction: str = "mean"


@dataclass
class MultiMarginLossConf:
    _target_: str = "torch.nn.modules.loss.MultiMarginLoss"
    p: int = 1
    margin: float = 1.0
    weight: Any = MISSING  # Optional[Tensor]
    size_average: Any = None
    reduce: Any = None
    reduction: str = "mean"


@dataclass
class NLLLossConf:
    _target_: str = "torch.nn.modules.loss.NLLLoss"
    weight: Any = MISSING  # Optional[Tensor]
    size_average: Any = None
    ignore_index: int = -100
    reduce: Any = None
    reduction: str = "mean"


@dataclass
class NLLLoss2dConf:
    _target_: str = "torch.nn.modules.loss.NLLLoss2d"
    weight: Any = MISSING  # Optional[Tensor]
    size_average: Any = None
    ignore_index: int = -100
    reduce: Any = None
    reduction: str = "mean"


@dataclass
class PoissonNLLLossConf:
    _target_: str = "torch.nn.modules.loss.PoissonNLLLoss"
    log_input: bool = True
    full: bool = False
    size_average: Any = None
    eps: float = 1e-08
    reduce: Any = None
    reduction: str = "mean"


@dataclass
class SmoothL1LossConf:
    _target_: str = "torch.nn.modules.loss.SmoothL1Loss"
    size_average: Any = None
    reduce: Any = None
    reduction: str = "mean"


@dataclass
class SoftMarginLossConf:
    _target_: str = "torch.nn.modules.loss.SoftMarginLoss"
    size_average: Any = None
    reduce: Any = None
    reduction: str = "mean"


@dataclass
class TripletMarginLossConf:
    _target_: str = "torch.nn.modules.loss.TripletMarginLoss"
    margin: float = 1.0
    p: float = 2.0
    eps: float = 1e-06
    swap: bool = False
    size_average: Any = None
    reduce: Any = None
    reduction: str = "mean"
