# Copyright (c) 2020, Facebook, Inc. and its affiliates. All Rights Reserved
# SPDX-License-Identifier: MIT
#
# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from omegaconf import MISSING
from typing import Any


@dataclass
class RMSpropConf:
    """For more details on parameteres please refer to the original documentation:
    https://pytorch.org/docs/stable/optim.html#torch.optim.RMSprop
    """
    _target_: str = "torch.optim.rmsprop.RMSprop"
    params: Any = MISSING
    lr: Any = 0.01
    alpha: Any = 0.99
    eps: Any = 1e-08
    weight_decay: Any = 0
    momentum: Any = 0
    centered: Any = False
